"""Catalogue de base COOP'ACT — 15 produits avec formats et infos alimentaires pré-remplis (upsert idempotent)."""
BASE_15 = [
 {"sku": "RIZ-LONG-1KG", "name": "Riz long grain blanc 1kg", "category": "epicerie",
  "food_info": {"format_label": "1 kg", "net_qty_value": 1, "net_qty_unit": "kg",
                "ingredients": "Riz long grain blanc 100 %", "allergens": "Aucun",
                "lot_composition": "3 sachets de 1 kg — 3 kg"}},
 {"sku": "PATES-500G", "name": "Coquillettes sèches 500g", "category": "epicerie",
  "food_info": {"format_label": "500 g", "net_qty_value": 500, "net_qty_unit": "g",
                "ingredients": "Semoule de blé dur de qualité supérieure", "allergens": "Gluten (blé)",
                "lot_composition": "3 paquets de 500 g — 1,5 kg"}},
 {"sku": "FARINE-1KG", "name": "Farine de blé T55 1kg", "category": "epicerie",
  "food_info": {"format_label": "1 kg", "net_qty_value": 1, "net_qty_unit": "kg",
                "ingredients": "Farine de blé T55", "allergens": "Gluten (blé)",
                "lot_composition": "3 paquets de 1 kg — 3 kg"}},
 {"sku": "SUCRE-CANNE-RE-1KG", "name": "Sucre de canne roux 1kg", "category": "epicerie",
  "food_info": {"format_label": "1 kg", "net_qty_value": 1, "net_qty_unit": "kg",
                "ingredients": "Sucre de canne roux pur", "allergens": "Aucun",
                "lot_composition": "3 paquets de 1 kg — 3 kg"}},
 {"sku": "HUILE-1L", "name": "Huile de tournesol 1L", "category": "epicerie",
  "food_info": {"format_label": "1 L", "net_qty_value": 1, "net_qty_unit": "L",
                "ingredients": "Huile de tournesol 100 %", "allergens": "Aucun",
                "lot_composition": "3 bouteilles de 1 litre — 3 L"}},
 {"sku": "LAIT-1L", "name": "Lait demi-écrémé UHT 1L", "category": "frais",
  "food_info": {"format_label": "1 L", "net_qty_value": 1, "net_qty_unit": "L",
                "ingredients": "Lait demi-écrémé stérilisé UHT", "allergens": "Lait",
                "lot_composition": "3 briques de 1 litre — 3 L"}},
 {"sku": "LENTILLES-500G", "name": "Lentilles vertes sèches 500g", "category": "epicerie",
  "food_info": {"format_label": "500 g", "net_qty_value": 500, "net_qty_unit": "g",
                "ingredients": "Lentilles vertes sèches", "allergens": "Aucun (traces possibles de gluten)",
                "lot_composition": "3 sachets de 500 g — 1,5 kg"}},
 {"sku": "HARICOTS-RGS-400G", "name": "Haricots rouges cuits au naturel 400g", "category": "conserves",
  "food_info": {"format_label": "400 g net", "net_qty_value": 400, "net_qty_unit": "g",
                "ingredients": "Haricots rouges, eau, sel", "allergens": "Aucun",
                "lot_composition": "3 conserves de 400 g net — 1,2 kg net"}},
 {"sku": "POIS-ANGOLE-800G", "name": "Pois d'angole en sachet 800g", "category": "epicerie",
  "food_info": {"format_label": "800 g net", "net_qty_value": 800, "net_qty_unit": "g",
                "ingredients": "Pois d'angole (pois de bois)", "allergens": "Aucun",
                "lot_composition": "3 sachets de 800 g net — 2,4 kg net"}},
 {"sku": "THON-160G", "name": "Thon en morceaux au naturel 160g", "category": "conserves",
  "food_info": {"format_label": "160 g net", "net_qty_value": 160, "net_qty_unit": "g",
                "ingredients": "Thon, eau, sel", "allergens": "Poisson",
                "lot_composition": "3 conserves de 160 g net — 480 g net"}},
 {"sku": "SARDINES-125G", "name": "Sardines à l'huile 125g", "category": "conserves",
  "food_info": {"format_label": "125 g net", "net_qty_value": 125, "net_qty_unit": "g",
                "ingredients": "Sardines, huile de tournesol, sel", "allergens": "Poisson",
                "lot_composition": "3 conserves de 125 g net — 375 g net"}},
 {"sku": "CAFE-250G", "name": "Café moulu 250g", "category": "epicerie",
  "food_info": {"format_label": "250 g", "net_qty_value": 250, "net_qty_unit": "g",
                "ingredients": "Café moulu 100 % (arabica/robusta selon marque annoncée)", "allergens": "Aucun",
                "lot_composition": "3 sachets de 250 g — 750 g"}},
 {"sku": "LP-CAP-CONFITURE-DE-GOYAV-53A0", "name": "Confiture de goyave 250g", "category": "epicerie",
  "food_info": {"format_label": "250 g", "net_qty_value": 250, "net_qty_unit": "g",
                "ingredients": "Goyave, sucre de canne, jus de citron, pectine", "allergens": "Aucun",
                "lot_composition": "3 pots de 250 g — 750 g"}},
 {"sku": "NECTAR-GOYAVE-1L", "name": "Nectar de goyave longue conservation 1L", "category": "boissons",
  "food_info": {"format_label": "1 L", "net_qty_value": 1, "net_qty_unit": "L",
                "ingredients": "Purée de goyave, eau, sucre, acidifiant : acide citrique", "allergens": "Aucun",
                "lot_composition": "3 briques ou bouteilles de 1 litre — 3 L"}},
 {"sku": "SAUCE-TOMATE-400G", "name": "Sauce tomate nature 400g", "category": "conserves",
  "food_info": {"format_label": "400 g", "net_qty_value": 400, "net_qty_unit": "g",
                "ingredients": "Tomates, sel", "allergens": "Aucun",
                "lot_composition": "3 bocaux de 400 g — 1,2 kg"}},
]


async def seed_food_catalog(db):
    for p in BASE_15:
        await db.lolodrive_products.update_one(
            {"sku": p["sku"]},
            {"$set": {"name": p["name"], "food_info": p["food_info"], "detaillant_active": True},
             "$setOnInsert": {"sku": p["sku"], "category": p["category"], "price_type": "NORMAL"}},
            upsert=True)
