export const LANGS = [
  { code: 'fr', flag: '🇫🇷', label: 'Français' },
  { code: 'en', flag: '🇬🇧', label: 'English' },
  { code: 'es', flag: '🇪🇸', label: 'Español' },
];

export const PHONE_COUNTRIES = [
  { code: 'GP', flag: '🇬🇵', dial: '+590', name: 'Guadeloupe' },
  { code: 'MQ', flag: '🇲🇶', dial: '+596', name: 'Martinique' },
  { code: 'GF', flag: '🇬🇫', dial: '+594', name: 'Guyane' },
  { code: 'RE', flag: '🇷🇪', dial: '+262', name: 'La Réunion' },
  { code: 'YT', flag: '🇾🇹', dial: '+262', name: 'Mayotte' },
  { code: 'FR', flag: '🇫🇷', dial: '+33', name: 'France' },
  { code: 'MF', flag: '🇲🇫', dial: '+590', name: 'Saint-Martin' },
  { code: 'BE', flag: '🇧🇪', dial: '+32', name: 'Belgique' },
  { code: 'CH', flag: '🇨🇭', dial: '+41', name: 'Suisse' },
  { code: 'ES', flag: '🇪🇸', dial: '+34', name: 'España' },
  { code: 'GB', flag: '🇬🇧', dial: '+44', name: 'United Kingdom' },
  { code: 'US', flag: '🇺🇸', dial: '+1', name: 'USA' },
  { code: 'CA', flag: '🇨🇦', dial: '+1', name: 'Canada' },
  { code: 'HT', flag: '🇭🇹', dial: '+509', name: 'Haïti' },
  { code: 'DO', flag: '🇩🇴', dial: '+1809', name: 'Rep. Dominicana' },
  { code: 'BR', flag: '🇧🇷', dial: '+55', name: 'Brasil' },
];

export const LEGAL_STATUSES = ['SARL', 'SAS', 'SASU', 'EURL', 'SA', 'SCOP', 'SCIC', 'EI / Micro-entreprise', 'Association', 'GIE', 'Coopérative', 'Autre'];

export const FORM_T = {
  fr: {
    company_label: 'Raison sociale *',
    company_placeholder: 'Nom légal de votre entreprise',
    legal_label: 'Statut juridique *',
    legal_placeholder: 'Sélectionnez un statut',
    firstname_label: 'Prénom du contact *',
    firstname_placeholder: 'Prénom',
    lastname_label: 'Nom du contact *',
    lastname_placeholder: 'Nom',
    email_label: 'Email professionnel *',
    phone_label: 'Téléphone *',
    phone_placeholder: '690 00 00 00',
    message_label: 'Message / Besoins spécifiques',
    message_placeholder: 'Décrivez votre activité, vos besoins, vos questions…',
    send: 'Envoyer ma demande de devis',
    sending: 'Envoi en cours…',
    disclaimer: "En soumettant ce formulaire, vous acceptez d'être contacté par notre équipe commerciale.",
    sent_title: 'Demande envoyée !',
    sent_desc: 'Notre équipe commerciale vous recontacte sous 48h ouvrées.',
    toast_success: 'Votre demande de devis a bien été envoyée',
    toast_error: "Une erreur est survenue, veuillez réessayer",
  },
  en: {
    company_label: 'Company name *',
    company_placeholder: 'Legal name of your company',
    legal_label: 'Legal status *',
    legal_placeholder: 'Select a status',
    firstname_label: 'Contact first name *',
    firstname_placeholder: 'First name',
    lastname_label: 'Contact last name *',
    lastname_placeholder: 'Last name',
    email_label: 'Business email *',
    phone_label: 'Phone *',
    phone_placeholder: '690 00 00 00',
    message_label: 'Message / Specific needs',
    message_placeholder: 'Describe your business, your needs, your questions…',
    send: 'Send my quote request',
    sending: 'Sending…',
    disclaimer: 'By submitting this form, you agree to be contacted by our sales team.',
    sent_title: 'Request sent!',
    sent_desc: 'Our sales team will get back to you within 48 business hours.',
    toast_success: 'Your quote request has been sent',
    toast_error: 'An error occurred, please try again',
  },
  es: {
    company_label: 'Razón social *',
    company_placeholder: 'Nombre legal de su empresa',
    legal_label: 'Forma jurídica *',
    legal_placeholder: 'Seleccione una forma',
    firstname_label: 'Nombre del contacto *',
    firstname_placeholder: 'Nombre',
    lastname_label: 'Apellido del contacto *',
    lastname_placeholder: 'Apellido',
    email_label: 'Correo profesional *',
    phone_label: 'Teléfono *',
    phone_placeholder: '690 00 00 00',
    message_label: 'Mensaje / Necesidades específicas',
    message_placeholder: 'Describa su actividad, sus necesidades, sus preguntas…',
    send: 'Enviar mi solicitud de presupuesto',
    sending: 'Enviando…',
    disclaimer: 'Al enviar este formulario, acepta ser contactado por nuestro equipo comercial.',
    sent_title: '¡Solicitud enviada!',
    sent_desc: 'Nuestro equipo comercial le responderá en 48 horas laborables.',
    toast_success: 'Su solicitud de presupuesto ha sido enviada',
    toast_error: 'Se produjo un error, inténtelo de nuevo',
  },
};
