// Liste complète des pays avec indicatifs internationaux (noms français, codes ISO 3166-1)
export const PRIORITY_COUNTRIES = [
  { code: 'FR', name: 'France', prefix: '+33' },
  { code: 'GP', name: 'Guadeloupe', prefix: '+590' },
  { code: 'MQ', name: 'Martinique', prefix: '+596' },
  { code: 'GF', name: 'Guyane', prefix: '+594' },
  { code: 'RE', name: 'La Réunion', prefix: '+262' },
  { code: 'YT', name: 'Mayotte', prefix: '+262' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', prefix: '+508' },
  { code: 'BL', name: 'Saint-Barthélemy', prefix: '+590' },
  { code: 'MF', name: 'Saint-Martin', prefix: '+590' },
  { code: 'PF', name: 'Polynésie française', prefix: '+689' },
  { code: 'NC', name: 'Nouvelle-Calédonie', prefix: '+687' },
  { code: 'WF', name: 'Wallis-et-Futuna', prefix: '+681' },
];

export const WORLD_COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', prefix: '+93' },
  { code: 'ZA', name: 'Afrique du Sud', prefix: '+27' },
  { code: 'AL', name: 'Albanie', prefix: '+355' },
  { code: 'DZ', name: 'Algérie', prefix: '+213' },
  { code: 'DE', name: 'Allemagne', prefix: '+49' },
  { code: 'AD', name: 'Andorre', prefix: '+376' },
  { code: 'AO', name: 'Angola', prefix: '+244' },
  { code: 'AI', name: 'Anguilla', prefix: '+1264' },
  { code: 'AG', name: 'Antigua-et-Barbuda', prefix: '+1268' },
  { code: 'SA', name: 'Arabie saoudite', prefix: '+966' },
  { code: 'AR', name: 'Argentine', prefix: '+54' },
  { code: 'AM', name: 'Arménie', prefix: '+374' },
  { code: 'AW', name: 'Aruba', prefix: '+297' },
  { code: 'AU', name: 'Australie', prefix: '+61' },
  { code: 'AT', name: 'Autriche', prefix: '+43' },
  { code: 'AZ', name: 'Azerbaïdjan', prefix: '+994' },
  { code: 'BS', name: 'Bahamas', prefix: '+1242' },
  { code: 'BH', name: 'Bahreïn', prefix: '+973' },
  { code: 'BD', name: 'Bangladesh', prefix: '+880' },
  { code: 'BB', name: 'Barbade', prefix: '+1246' },
  { code: 'BE', name: 'Belgique', prefix: '+32' },
  { code: 'BZ', name: 'Belize', prefix: '+501' },
  { code: 'BJ', name: 'Bénin', prefix: '+229' },
  { code: 'BM', name: 'Bermudes', prefix: '+1441' },
  { code: 'BT', name: 'Bhoutan', prefix: '+975' },
  { code: 'BY', name: 'Biélorussie', prefix: '+375' },
  { code: 'BO', name: 'Bolivie', prefix: '+591' },
  { code: 'BA', name: 'Bosnie-Herzégovine', prefix: '+387' },
  { code: 'BW', name: 'Botswana', prefix: '+267' },
  { code: 'BR', name: 'Brésil', prefix: '+55' },
  { code: 'BN', name: 'Brunei', prefix: '+673' },
  { code: 'BG', name: 'Bulgarie', prefix: '+359' },
  { code: 'BF', name: 'Burkina Faso', prefix: '+226' },
  { code: 'BI', name: 'Burundi', prefix: '+257' },
  { code: 'KH', name: 'Cambodge', prefix: '+855' },
  { code: 'CM', name: 'Cameroun', prefix: '+237' },
  { code: 'CA', name: 'Canada', prefix: '+1' },
  { code: 'CV', name: 'Cap-Vert', prefix: '+238' },
  { code: 'CL', name: 'Chili', prefix: '+56' },
  { code: 'CN', name: 'Chine', prefix: '+86' },
  { code: 'CY', name: 'Chypre', prefix: '+357' },
  { code: 'CO', name: 'Colombie', prefix: '+57' },
  { code: 'KM', name: 'Comores', prefix: '+269' },
  { code: 'CG', name: 'Congo (Brazzaville)', prefix: '+242' },
  { code: 'CD', name: 'Congo (RDC)', prefix: '+243' },
  { code: 'KR', name: 'Corée du Sud', prefix: '+82' },
  { code: 'CR', name: 'Costa Rica', prefix: '+506' },
  { code: 'CI', name: "Côte d'Ivoire", prefix: '+225' },
  { code: 'HR', name: 'Croatie', prefix: '+385' },
  { code: 'CU', name: 'Cuba', prefix: '+53' },
  { code: 'CW', name: 'Curaçao', prefix: '+599' },
  { code: 'DK', name: 'Danemark', prefix: '+45' },
  { code: 'DJ', name: 'Djibouti', prefix: '+253' },
  { code: 'DM', name: 'Dominique', prefix: '+1767' },
  { code: 'EG', name: 'Égypte', prefix: '+20' },
  { code: 'AE', name: 'Émirats arabes unis', prefix: '+971' },
  { code: 'EC', name: 'Équateur', prefix: '+593' },
  { code: 'ER', name: 'Érythrée', prefix: '+291' },
  { code: 'ES', name: 'Espagne', prefix: '+34' },
  { code: 'EE', name: 'Estonie', prefix: '+372' },
  { code: 'SZ', name: 'Eswatini', prefix: '+268' },
  { code: 'US', name: 'États-Unis', prefix: '+1' },
  { code: 'ET', name: 'Éthiopie', prefix: '+251' },
  { code: 'FJ', name: 'Fidji', prefix: '+679' },
  { code: 'FI', name: 'Finlande', prefix: '+358' },
  { code: 'GA', name: 'Gabon', prefix: '+241' },
  { code: 'GM', name: 'Gambie', prefix: '+220' },
  { code: 'GE', name: 'Géorgie', prefix: '+995' },
  { code: 'GH', name: 'Ghana', prefix: '+233' },
  { code: 'GI', name: 'Gibraltar', prefix: '+350' },
  { code: 'GR', name: 'Grèce', prefix: '+30' },
  { code: 'GD', name: 'Grenade', prefix: '+1473' },
  { code: 'GL', name: 'Groenland', prefix: '+299' },
  { code: 'GT', name: 'Guatemala', prefix: '+502' },
  { code: 'GN', name: 'Guinée', prefix: '+224' },
  { code: 'GQ', name: 'Guinée équatoriale', prefix: '+240' },
  { code: 'GW', name: 'Guinée-Bissau', prefix: '+245' },
  { code: 'GY', name: 'Guyana', prefix: '+592' },
  { code: 'HT', name: 'Haïti', prefix: '+509' },
  { code: 'HN', name: 'Honduras', prefix: '+504' },
  { code: 'HK', name: 'Hong Kong', prefix: '+852' },
  { code: 'HU', name: 'Hongrie', prefix: '+36' },
  { code: 'IN', name: 'Inde', prefix: '+91' },
  { code: 'ID', name: 'Indonésie', prefix: '+62' },
  { code: 'IQ', name: 'Irak', prefix: '+964' },
  { code: 'IR', name: 'Iran', prefix: '+98' },
  { code: 'IE', name: 'Irlande', prefix: '+353' },
  { code: 'IS', name: 'Islande', prefix: '+354' },
  { code: 'IL', name: 'Israël', prefix: '+972' },
  { code: 'IT', name: 'Italie', prefix: '+39' },
  { code: 'JM', name: 'Jamaïque', prefix: '+1876' },
  { code: 'JP', name: 'Japon', prefix: '+81' },
  { code: 'JO', name: 'Jordanie', prefix: '+962' },
  { code: 'KZ', name: 'Kazakhstan', prefix: '+7' },
  { code: 'KE', name: 'Kenya', prefix: '+254' },
  { code: 'KG', name: 'Kirghizistan', prefix: '+996' },
  { code: 'KW', name: 'Koweït', prefix: '+965' },
  { code: 'LA', name: 'Laos', prefix: '+856' },
  { code: 'LS', name: 'Lesotho', prefix: '+266' },
  { code: 'LV', name: 'Lettonie', prefix: '+371' },
  { code: 'LB', name: 'Liban', prefix: '+961' },
  { code: 'LR', name: 'Liberia', prefix: '+231' },
  { code: 'LY', name: 'Libye', prefix: '+218' },
  { code: 'LI', name: 'Liechtenstein', prefix: '+423' },
  { code: 'LT', name: 'Lituanie', prefix: '+370' },
  { code: 'LU', name: 'Luxembourg', prefix: '+352' },
  { code: 'MO', name: 'Macao', prefix: '+853' },
  { code: 'MK', name: 'Macédoine du Nord', prefix: '+389' },
  { code: 'MG', name: 'Madagascar', prefix: '+261' },
  { code: 'MY', name: 'Malaisie', prefix: '+60' },
  { code: 'MW', name: 'Malawi', prefix: '+265' },
  { code: 'MV', name: 'Maldives', prefix: '+960' },
  { code: 'ML', name: 'Mali', prefix: '+223' },
  { code: 'MT', name: 'Malte', prefix: '+356' },
  { code: 'MA', name: 'Maroc', prefix: '+212' },
  { code: 'MU', name: 'Maurice', prefix: '+230' },
  { code: 'MR', name: 'Mauritanie', prefix: '+222' },
  { code: 'MX', name: 'Mexique', prefix: '+52' },
  { code: 'MD', name: 'Moldavie', prefix: '+373' },
  { code: 'MC', name: 'Monaco', prefix: '+377' },
  { code: 'MN', name: 'Mongolie', prefix: '+976' },
  { code: 'ME', name: 'Monténégro', prefix: '+382' },
  { code: 'MS', name: 'Montserrat', prefix: '+1664' },
  { code: 'MZ', name: 'Mozambique', prefix: '+258' },
  { code: 'MM', name: 'Myanmar (Birmanie)', prefix: '+95' },
  { code: 'NA', name: 'Namibie', prefix: '+264' },
  { code: 'NP', name: 'Népal', prefix: '+977' },
  { code: 'NI', name: 'Nicaragua', prefix: '+505' },
  { code: 'NE', name: 'Niger', prefix: '+227' },
  { code: 'NG', name: 'Nigeria', prefix: '+234' },
  { code: 'NO', name: 'Norvège', prefix: '+47' },
  { code: 'NZ', name: 'Nouvelle-Zélande', prefix: '+64' },
  { code: 'OM', name: 'Oman', prefix: '+968' },
  { code: 'UG', name: 'Ouganda', prefix: '+256' },
  { code: 'UZ', name: 'Ouzbékistan', prefix: '+998' },
  { code: 'PK', name: 'Pakistan', prefix: '+92' },
  { code: 'PA', name: 'Panama', prefix: '+507' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', prefix: '+675' },
  { code: 'PY', name: 'Paraguay', prefix: '+595' },
  { code: 'NL', name: 'Pays-Bas', prefix: '+31' },
  { code: 'PE', name: 'Pérou', prefix: '+51' },
  { code: 'PH', name: 'Philippines', prefix: '+63' },
  { code: 'PL', name: 'Pologne', prefix: '+48' },
  { code: 'PR', name: 'Porto Rico', prefix: '+1787' },
  { code: 'PT', name: 'Portugal', prefix: '+351' },
  { code: 'QA', name: 'Qatar', prefix: '+974' },
  { code: 'DO', name: 'République dominicaine', prefix: '+1809' },
  { code: 'CF', name: 'République centrafricaine', prefix: '+236' },
  { code: 'CZ', name: 'République tchèque', prefix: '+420' },
  { code: 'RO', name: 'Roumanie', prefix: '+40' },
  { code: 'GB', name: 'Royaume-Uni', prefix: '+44' },
  { code: 'RU', name: 'Russie', prefix: '+7' },
  { code: 'RW', name: 'Rwanda', prefix: '+250' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', prefix: '+1869' },
  { code: 'SM', name: 'Saint-Marin', prefix: '+378' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', prefix: '+1784' },
  { code: 'LC', name: 'Sainte-Lucie', prefix: '+1758' },
  { code: 'SB', name: 'Salomon', prefix: '+677' },
  { code: 'SV', name: 'Salvador', prefix: '+503' },
  { code: 'WS', name: 'Samoa', prefix: '+685' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', prefix: '+239' },
  { code: 'SN', name: 'Sénégal', prefix: '+221' },
  { code: 'RS', name: 'Serbie', prefix: '+381' },
  { code: 'SC', name: 'Seychelles', prefix: '+248' },
  { code: 'SL', name: 'Sierra Leone', prefix: '+232' },
  { code: 'SG', name: 'Singapour', prefix: '+65' },
  { code: 'SX', name: 'Sint Maarten', prefix: '+1721' },
  { code: 'SK', name: 'Slovaquie', prefix: '+421' },
  { code: 'SI', name: 'Slovénie', prefix: '+386' },
  { code: 'SO', name: 'Somalie', prefix: '+252' },
  { code: 'SD', name: 'Soudan', prefix: '+249' },
  { code: 'SS', name: 'Soudan du Sud', prefix: '+211' },
  { code: 'LK', name: 'Sri Lanka', prefix: '+94' },
  { code: 'SE', name: 'Suède', prefix: '+46' },
  { code: 'CH', name: 'Suisse', prefix: '+41' },
  { code: 'SR', name: 'Suriname', prefix: '+597' },
  { code: 'SY', name: 'Syrie', prefix: '+963' },
  { code: 'TJ', name: 'Tadjikistan', prefix: '+992' },
  { code: 'TW', name: 'Taïwan', prefix: '+886' },
  { code: 'TZ', name: 'Tanzanie', prefix: '+255' },
  { code: 'TD', name: 'Tchad', prefix: '+235' },
  { code: 'TH', name: 'Thaïlande', prefix: '+66' },
  { code: 'TL', name: 'Timor oriental', prefix: '+670' },
  { code: 'TG', name: 'Togo', prefix: '+228' },
  { code: 'TO', name: 'Tonga', prefix: '+676' },
  { code: 'TT', name: 'Trinité-et-Tobago', prefix: '+1868' },
  { code: 'TN', name: 'Tunisie', prefix: '+216' },
  { code: 'TM', name: 'Turkménistan', prefix: '+993' },
  { code: 'TR', name: 'Turquie', prefix: '+90' },
  { code: 'UA', name: 'Ukraine', prefix: '+380' },
  { code: 'UY', name: 'Uruguay', prefix: '+598' },
  { code: 'VU', name: 'Vanuatu', prefix: '+678' },
  { code: 'VE', name: 'Venezuela', prefix: '+58' },
  { code: 'VN', name: 'Vietnam', prefix: '+84' },
  { code: 'YE', name: 'Yémen', prefix: '+967' },
  { code: 'ZM', name: 'Zambie', prefix: '+260' },
  { code: 'ZW', name: 'Zimbabwe', prefix: '+263' },
];

export const ALL_COUNTRIES = [...PRIORITY_COUNTRIES, ...WORLD_COUNTRIES];
